[platformio]
default_envs = avi_99l_missionboard

[env:avi_99l_missionboard]
platform = espressif32@7.0.1
board = avi_99l_missionboard
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
lib_deps =
    https://github.com/CREATE-ROCKET/Avi_ESP_Libs.git#2562ef05d3f7673a5681d8a3739c874f95811c73
build_flags =
    -std=gnu++17
    -Wno-error=pedantic